import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/account/account_providers.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/widgets/account_sheet.dart';
import '../../core/widgets/async_error_view.dart';
import '../../core/widgets/ledger_surface.dart';
import 'models/action_item.dart';
import 'today_providers.dart';

/// The Today tab: a unified action feed spanning every engine — quotes to
/// close (MAKE), returns/warranties needing attention (PROTECT), and
/// resell opportunities (RECOVER) — surfaced as one prioritized list.
///
/// Mirrors `apps/web/src/app/(app)/today/page.tsx`: backed by
/// `public.actions`, which now includes both manually/AI-created rows and
/// ones auto-generated by `generate_today_actions` (quote follow-ups,
/// return/warranty deadlines) — see today_providers.dart.
class TodayScreen extends ConsumerWidget {
  const TodayScreen({super.key});

  void _showQuickAdd(BuildContext context) {
    showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      showDragHandle: true,
      builder: (sheetContext) => SafeArea(
        child: AnimatedPadding(
          duration: const Duration(milliseconds: 160),
          padding: EdgeInsets.fromLTRB(
            AppSpacing.md,
            AppSpacing.xs,
            AppSpacing.md,
            MediaQuery.viewInsetsOf(sheetContext).bottom + AppSpacing.md,
          ),
          child: _QuickAddForm(
            autofocus: true,
            onAdded: () => Navigator.of(sheetContext).pop(),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final actionsAsync = ref.watch(todayActionsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Today'),
        actions: [
          IconButton(
            tooltip: 'Add action',
            onPressed: () => _showQuickAdd(context),
            icon: const Icon(Icons.add),
          ),
          const AccountAvatarButton(),
        ],
      ),
      body: SafeArea(
        child: RefreshIndicator(
          onRefresh: () => ref.refresh(todayActionsProvider.future),
          child: actionsAsync.when(
            data: (actions) => _TodayList(
              actions: actions,
              onAdd: () => _showQuickAdd(context),
            ),
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (error, _) => AsyncErrorView(
              error: error,
              onRetry: () => ref.invalidate(todayActionsProvider),
            ),
          ),
        ),
      ),
    );
  }
}

class _TodayList extends ConsumerWidget {
  const _TodayList({required this.actions, required this.onAdd});

  final List<ActionItem> actions;
  final VoidCallback onAdd;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final open = actions
        .where(
          (a) =>
              a.status == ActionStatus.open || a.status == ActionStatus.snoozed,
        )
        .toList();
    final done = actions
        .where((a) => a.status == ActionStatus.done)
        .take(2)
        .toList();

    final theme = Theme.of(context);
    return ListView(
      padding: const EdgeInsets.all(AppSpacing.md),
      children: [
        LedgerPageIntro(
          title: 'Today',
          subtitle: _formatFullDate(DateTime.now()),
        ),
        const SizedBox(height: AppSpacing.xl),
        if (open.isEmpty)
          LedgerEmptyState(
            title: 'You’re clear.',
            detail: 'Nothing needs your attention right now.',
            action: FilledButton.icon(
              key: const Key('today-empty-add-action'),
              onPressed: onAdd,
              icon: const Icon(Icons.add),
              label: const Text('Add an action'),
            ),
          )
        else ...[
          _NextAction(action: open.first),
          if (open.length > 1) ...[
            const SizedBox(height: AppSpacing.lg),
            const LedgerSectionLabel('Up next'),
            const SizedBox(height: AppSpacing.xs),
            ...open
                .skip(1)
                .take(4)
                .map((action) => _ActionTile(action: action)),
            if (open.length > 5)
              Padding(
                padding: const EdgeInsets.only(top: AppSpacing.sm),
                child: Text(
                  '${open.length - 5} more waiting',
                  style: theme.textTheme.bodyMedium,
                ),
              ),
          ],
        ],
        if (done.isNotEmpty) ...[
          const SizedBox(height: AppSpacing.lg),
          const LedgerSectionLabel('Recently done'),
          const SizedBox(height: AppSpacing.xs),
          ...done.map((action) => _DoneActionTile(action: action)),
        ],
      ],
    );
  }
}

class _QuickAddForm extends ConsumerStatefulWidget {
  const _QuickAddForm({this.autofocus = false, this.onAdded});

  final bool autofocus;
  final VoidCallback? onAdded;

  @override
  ConsumerState<_QuickAddForm> createState() => _QuickAddFormState();
}

class _QuickAddFormState extends ConsumerState<_QuickAddForm> {
  final _controller = TextEditingController();
  bool _submitting = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final title = _controller.text.trim();
    if (title.isEmpty) return;

    setState(() => _submitting = true);
    try {
      final accountId = ref.read(activeAccountProvider).id;
      await ref
          .read(todayActionsRepositoryProvider)
          .quickAdd(accountId: accountId, title: title);
      if (!mounted) return;
      _controller.clear();
      ref.invalidate(todayActionsProvider);
      widget.onAdded?.call();
    } catch (_) {
      if (mounted) {
        showErrorSnackBar(context, userSafeActionError('add this action'));
      }
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          child: TextField(
            controller: _controller,
            autofocus: widget.autofocus,
            decoration: const InputDecoration(
              labelText: 'Action',
              hintText: 'What needs doing?',
              border: OutlineInputBorder(),
              isDense: true,
            ),
            onSubmitted: (_) => _submit(),
          ),
        ),
        const SizedBox(width: AppSpacing.sm),
        FilledButton(
          onPressed: _submitting ? null : _submit,
          child: _submitting
              ? const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Text('Save'),
        ),
      ],
    );
  }
}

Future<void> _setActionStatus({
  required WidgetRef ref,
  required BuildContext context,
  required ActionItem action,
  required ActionStatus status,
}) async {
  try {
    await ref
        .read(todayActionsRepositoryProvider)
        .setStatus(id: action.id, status: status);
    if (!context.mounted) return;
    ref.invalidate(todayActionsProvider);
  } catch (_) {
    if (context.mounted) {
      showErrorSnackBar(context, userSafeActionError('update this action'));
    }
  }
}

class _NextAction extends ConsumerWidget {
  const _NextAction({required this.action});

  final ActionItem action;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    return LedgerHero(
      eyebrow: 'Next',
      value: Text(action.title, style: theme.textTheme.headlineMedium),
      detail: action.dueAt == null ? null : _dueText(action.dueAt!),
      action: Row(
        children: [
          FilledButton.icon(
            key: const Key('today-complete-next-action'),
            onPressed: () => _setActionStatus(
              ref: ref,
              context: context,
              action: action,
              status: ActionStatus.done,
            ),
            icon: const Icon(Icons.check),
            label: const Text('Mark done'),
          ),
          const SizedBox(width: AppSpacing.sm),
          IconButton(
            tooltip: 'Dismiss action',
            onPressed: () => _setActionStatus(
              ref: ref,
              context: context,
              action: action,
              status: ActionStatus.dismissed,
            ),
            icon: const Icon(Icons.close),
          ),
        ],
      ),
    );
  }
}

/// A ledger entry, not a card — Today's rows read as lines in a private
/// register (rule line below, no per-row surface/elevation) rather than
/// stacked Trello-style cards. See docs/DESIGN_SYSTEM.md.
class _ActionTile extends ConsumerWidget {
  const _ActionTile({required this.action});

  final ActionItem action;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return LedgerRow(
      title: action.title,
      subtitle: action.dueAt == null ? null : _dueText(action.dueAt!),
      trailing: IconButton(
        tooltip: 'Mark ${action.title} done',
        onPressed: () => _setActionStatus(
          ref: ref,
          context: context,
          action: action,
          status: ActionStatus.done,
        ),
        icon: const Icon(Icons.check_circle_outline),
      ),
    );
  }
}

class _DoneActionTile extends ConsumerWidget {
  const _DoneActionTile({required this.action});

  final ActionItem action;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);

    Future<void> reopen() async {
      try {
        await ref
            .read(todayActionsRepositoryProvider)
            .setStatus(id: action.id, status: ActionStatus.open);
        if (!context.mounted) return;
        ref.invalidate(todayActionsProvider);
      } catch (_) {
        if (context.mounted) {
          showErrorSnackBar(context, userSafeActionError('reopen this action'));
        }
      }
    }

    return Padding(
      padding: const EdgeInsets.only(bottom: AppSpacing.xs),
      child: Row(
        children: [
          Expanded(
            child: Text(
              action.title,
              style: theme.textTheme.bodyMedium?.copyWith(
                decoration: TextDecoration.lineThrough,
                color: theme.colorScheme.outline,
              ),
            ),
          ),
          TextButton(onPressed: reopen, child: const Text('Reopen')),
        ],
      ),
    );
  }
}

String _dueText(DateTime dueAt) {
  final overdue = dueAt.isBefore(DateTime.now());
  return '${overdue ? 'Overdue · ' : 'Due '}${_formatDate(dueAt)}';
}

String _formatFullDate(DateTime date) {
  const weekdays = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ];
  const months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];
  return '${weekdays[date.weekday - 1]}, ${months[date.month - 1]} ${date.day}';
}

String _formatDate(DateTime date) {
  const months = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ];
  final now = DateTime.now();
  if (date.year == now.year && date.month == now.month && date.day == now.day) {
    return 'Today';
  }
  return '${months[date.month - 1]} ${date.day}';
}
